---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Install Docker
    yum:
      name: docker-1.13.1
  - name: Add INSECURE Registry
    lineinfile:
      dest: /etc/sysconfig/docker
      line: 'INSECURE_REGISTRY="--insecure-registry 172.30.0.0/16"'
  - name: Add overlay2
    lineinfile:
      dest: /etc/sysconfig/docker-storage-setup
      line: 'STORAGE_DRIVER=overlay2'
  - name: Enable Docker
    systemd: name=docker enabled=yes
  - name: Restart docker
    command: systemctl restart docker 
