---
- hosts: all
  become: yes
  tasks:
  - name: Install NetworkManager
    yum: name=NetworkManager state=present
  - name: Enable NetworkManager
    systemd: name=NetworkManager daemon_reload=true enabled=yes
  - name: Restart NetworkManager
    command: systemctl restart NetworkManager
