---
- hosts: all
  become: true
  tasks:
  - name: Install NFS packages
    yum:
      name: autofs, nfs-utils
      state: present
  - name: Create /etc/auto.data
    copy:
      content: |
        src -rw,soft,intr 192.168.30.64:/home/aim/go-projects/origin/src
      dest: /etc/auto.data
      force: yes
      group: root
      owner: root
      mode: 0644
  - name: Add to /etc/auto.master
    copy:
      content: |
        /data /etc/auto.data
      dest: /etc/auto.master
      force: yes
      group: root
      owner: root
      mode: 0644
  - name: Create /etc/auto.kube
    copy:
      content: |
        src -rw,soft,intr 192.168.30.64:/home/aim/go-projects/kube/src
      dest: /etc/auto.kube
      force: yes
      group: root
      owner: root
      mode: 0644
  - name: Add to /etc/auto.master
    copy:
      content: |
        /kube /etc/auto.kube
      dest: /etc/auto.master
      force: yes
      group: root
      owner: root
      mode: 0644
  - name: Enable autofs
    systemd: name=autofs daemon_reload=true enabled=yes
  - name: Restart autofs
    command: systemctl restart autofs
