---
- import_playbook: network-manager.yaml

- import_playbook: update-packages.yaml

- import_playbook: prerequisites.yaml

- import_playbook: ansible-support.yaml

- import_playbook: docker.yaml

- import_playbook: docker-group.yaml

- import_playbook: docker-registry-mirror.yaml

- import_playbook: nfs.yaml

- import_playbook: 103-ssh.yaml

- import_playbook: origin-scripts.yaml

