---
- hosts: all
  tasks:
  - name: Install packages
    become: yes
    yum:
      name: git, bash-completion, bind-utils
      state: present
  - name: Clone Origin scripts
    git:
      repo: https://github.com/frobware/origin-scripts
      dest: origin-scripts
  - name: Create bash helpers
    blockinfile:
      dest: "{{ ansible_env.HOME }}/.bash_profile"
      block: |
        export PATH=/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64:$PATH
        type -p direnv &>/dev/null && eval "$(direnv hook bash)"
        type -p oc &>/dev/null && source <(oc completion bash)
        type -p kubectl &>/dev/null && source <(kubectl completion bash)
      marker: '# {mark} ANSIBLE MANAGED BLOCK - oc bash helpers'
      insertbefore: EOF
      create: yes
